name: websocket_server
channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.7
    #- numpy>=1.17.2
    #- pandas>=0.25.1
    #- psycopg2>=2.7.5
    #- pyodbc>=4.0.27
  - pytest>=5.2.1
    #- pytest-xdist>=1.30.0
    #- sqlalchemy-utils>=0.34.2
    #- sqlalchemy>=1.3.7
  #- supervisor>=4.1.0
    #- flask>=1.1.2
    #- flask-login>=0.5.0
  - aiohttp>=3.6.2
    #- lxml>=4.6.2
    #- mysql-connector-python>=8.0.0  
